config/routes.rb
Rails.application.routes.draw do

	ActiveAdmin.routes(self)
	root to: "enterprises#index"

	devise_for :users
	resources :enterprises
	resources :dishes
	resources :users

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter
  def authorized?(action, subject = nil)
    user.admin?
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :enterprise

	has_one_attached :picture
	validates :picture,  file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }

	validates :name, presence: true,
	length: { maximum: 250 }

	validates :price, presence: true,
	numericality: { greater_than_or_equal_to: 0 }
end

app/models/enterprise.rb
class Enterprise < ApplicationRecord
	has_many :dishes

	has_one_attached :picture
	validates :picture,  file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }

	validates :name, presence: true,
	length: { maximum: 250 }

	validates :price, presence: true,
	numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :picture
   # has_many_attached :pictures

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  before_action :logged_in_user, :admin_user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def access_denied(exception)
  	flash[:danger] = exception.message
  	redirect_to root_url
  end

  private

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  	devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in'
      redirect_to login_url
    end
  end

end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

	before_action :find_dish, only: [:show, :edit, :update, :destroy]

	def index
		@dishes = Dish.all
	end
	def new
		@dish = Dish.new
	end	
	def show

	end
	def create
		@dish = Dish.new(dish_params)
		
		if @dish.save
			upload_picture
			redirect_to dishes_path
		else
			render 'new'
		end
	end
	def edit

	end
	def update
		if @dish.update(dish_params)
			upload_picture
			redirect_to dish_path
		else
			render 'edit'
		end
	end
	def destroy
		@dish.destroy
		redirect_to dishes_path 
	end

	private

	def find_dish
		@dish = Dish.find(params[:id])
	end
	def dish_params
		params.require(:dish).permit(:name, :description, :price)
	end
	def upload_picture
		@dish.picture.attach(uploaded_file) if uploaded_file.present?
	end

	def uploaded_file
		params[:dish][:picture]
	end
end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController

	before_action :find_enterprise, only: [:show, :edit, :update, :destroy]

	def index
		@enterprises = Enterprise.all
	end
	def new
		@enterprise = Enterprise.new
	end	
	def show

	end
	def create
		@enterprise = Enterprise.new(enterprise_params)
		
		if @enterprise.save
			upload_picture
			redirect_to enterprises_path
		else
			render 'new'
		end
	end
	def edit

	end
	def update
		if @enterprise.update(enterprise_params)
			upload_picture
			redirect_to enterprise_path
		else
			render 'edit'
		end
	end
	def destroy
		@enterprise.destroy
		redirect_to enterprises_path 
	end

	private

	def find_enterprise
		@enterprise = Enterprise.find(params[:id])
	end
	def enterprise_params
		params.require(:enterprise).permit(:name, :dish_id, :description)
	end
	def upload_picture
		@enterprise.picture.attach(uploaded_file) if uploaded_file.present?
	end

	def uploaded_file
		params[:enterprise][:picture]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, only: [:show, :edit, :update, :destroy]

	def index
		@users = User.all
	end
	def show

	end
	def edit

	end
	def update
		if @user.update(user_params)
			upload_picture
			redirect_to user_path
		else
			render 'edit'
		end
	end
	def destroy
		@user.destroy
		redirect_to users_path 
	end

	private

	def find_user
		@user = User.find(params[:id])
	end
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :address)
	end
	def upload_picture
		@user.picture.attach(uploaded_file) if uploaded_file.present?
	end

	def uploaded_file
		params[:user][:picture]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dishes/_form.html.erb
<%= form_with model: [:admin, @dish], local: true do |f| %>

<% if @dish && @dish.errors.any? %>
<div class="errors">
	Total errors: <%= @dish.errors.count %>
	<ul>
		<% @dish.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<%= f.label :picture %><br />
	<%= f.file_field :picture %>
</div>

<div>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</div>

<div>
	<%= f.label :price %><br />
	<%= f.text_field :price %>
</div>

<div>
	<%= f.submit %>
</div>
<% end %>

app/views/dishes/edit.html.erb
<h1>Edit Dish</h1>

<%= render 'form' %>

app/views/dishes/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a><%= link_to 'Enterprises', enterprises_path, class: "nav-link btn btn-primary ml-2" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a><%= link_to 'Dishes', dishes_path, class: "nav-link btn btn-primary ml-2" %></a>
      </li>  
      <li class="nav-item ">
        <a> <%= link_to 'Users', users_path, class: "nav-link btn btn-primary ml-2" %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a> <%= link_to 'Sign up', new_user_registration_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log in', new_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log out', destroy_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
  </form>
</div>
</nav>

<div class="row">
  <div class="col-md-12">
    <h1>Dishes <%= link_to 'New Dish', new_dish_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr>

<table class="table table-striped">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Actions</th>
  </tr>

  <% @dishes.each do |dish| %>
      <tr>
        <td>
          <% if dish.picture.attached? %>
            <%= image_tag dish.picture, size: 100 %>
          <% end %>
        </td>
        <td><%= dish.name %></td>
        <td><%= dish.description %></td>
        <td><%= dish.price %></td>
        <td>
          <%= link_to 'View', dish_path(dish) %>
          <%= link_to 'Edit', edit_dish_path(dish) %>
          <%= link_to 'Delete', dish_path(dish),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form' %>

app/views/dishes/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a><%= link_to 'Enterprises', enterprises_path, class: "nav-link btn btn-primary ml-2" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a><%= link_to 'Dishes', dishes_path, class: "nav-link btn btn-primary ml-2" %></a>
      </li>  
      <li class="nav-item ">
        <a> <%= link_to 'Users', users_path, class: "nav-link btn btn-primary ml-2" %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a> <%= link_to 'Sign up', new_user_registration_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log in', new_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log out', destroy_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
  </form>
</div>
</nav>

<div>
  <div>
    <% if @dish.picture.attached? %>
    <%= image_tag @dish.picture, size: 100 %>
    <% end %>
  </div>
  <div>
  	<h1> <%= @dish.name %> </h1>
    <p> <%= @dish.description %> </p>
    <p> <%= @dish.price %> </p>
  </div>
</div>

app/views/enterprises/_form.html.erb
<%= form_with model: [:admin, @enterprise], local: true do |f| %>

<% if @enterprise && @enterprise.errors.any? %>
<div class="errors">
	Total errors: <%= @enterprise.errors.count %>
	<ul>
		<% @enterprise.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div>
	<%= f.label :picture %><br />
	<%= f.file_field :picture %>
</div>

<div>
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div>
	<%= f.label :description %><br />
	<%= f.text_area :description %>
</div>

<div>
	<%= f.label :dish %><br />
	<%= f.collection_select :dish_id, Dish.all, :id, :name %>
</div>

<div>
	<%= f.submit %>
</div>
<% end %>

app/views/enterprises/edit.html.erb
<h1>Edit Enterprise</h1>

<%= render 'form' %>

app/views/enterprises/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a><%= link_to 'Enterprises', enterprises_path, class: "nav-link btn btn-primary ml-2" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a><%= link_to 'Dishes', dishes_path, class: "nav-link btn btn-primary ml-2" %></a>
      </li>  
      <li class="nav-item ">
        <a> <%= link_to 'Users', users_path, class: "nav-link btn btn-primary ml-2" %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <% if current_user%>
      <p class="text-monospace ml-2 text-center "> Hello, <%= current_user.name %> </p>
      <% end %>
      <a> <%= link_to 'Sign up', new_user_registration_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log in', new_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log out', destroy_user_session_path , class: 'nav-link btn btn-primary ml-2', method: :delete %> </a>
    </form>
  </div>
</nav>

<table class="table table-striped">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Dishes</th>
    <th>Actions</th>
  </tr>

  <% @enterprises.each do |enterprise| %>
  <tr>
    <td>
      <% if enterprise.picture.attached? %>
      <%= image_tag enterprise.picture, size: 100 %>
      <% end %>
    </td>
    <td><%= enterprise.name %></td>
    <td><%= enterprise.description %></td>
    <td><%= enterprise.dishes.name %></td>
    <td>
      <%= link_to 'View', enterprise_path(enterprise) %>
      <%= link_to 'Edit', edit_enterprise_path(enterprise) %>
      <%= link_to 'Delete', enterprise_path(enterprise),
      method: :delete,
      data: {confirm: 'Do you want to remove this product?'}, class: "btn btn-primary" %>
    </td>
  </tr>
  <% end %>

</table>

app/views/enterprises/new.html.erb
<h1>New Enterprise</h1>

<%= render 'form' %>

app/views/enterprises/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a><%= link_to 'Enterprises', enterprises_path, class: "nav-link btn btn-primary ml-2" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a><%= link_to 'Dishes', dishes_path, class: "nav-link btn btn-primary ml-2" %></a>
      </li>  
      <li class="nav-item ">
        <a> <%= link_to 'Users', users_path, class: "nav-link btn btn-primary ml-2" %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a> <%= link_to 'Sign up', new_user_registration_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log in', new_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log out', destroy_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
  </form>
</div>
</nav>

<div>
  <div>
    <% if @enterprise.picture.attached? %>
    <%= image_tag @enterprise.picture, size: 100 %>
    <% end %>
  </div>
  <div>
  	<h1> <%= @enterprise.name %> </h1>
    <p> <%= @enterprise.dish.name %> </p>
    <p> <%= @enterprise.description %> </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab68</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar fixed-top navbar-dark bg-dark navbar-expand-md">
    <div class="container">
        <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          &#x2630;
        </button>

        <%= link_to 'Enterprise', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="nav-item"><a href="#" class="nav-link">About</a>
                </li>
                <li class="nav-item"><a href="#" class="nav-link">Contacts</a>
                </li>
            </ul>
            <div class="navbar-nav ml-auto">
              <% if user_signed_in? %>

              <div class="nav-item">
                <span class="navbar-text">
                  Hello,&nbsp;
                <span>
              </div>

              <div class="dropdown show">
                <%= link_to current_user.name, edit_user_registration_path(current_user), class: 'btn btn-secondary dropdown-toggle', 'role' => "button", 'id' => "dropdownMenuLink", 'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false" %>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to 'Edit profile', edit_user_registration_path(current_user), class: 'dropdown-item' %>
                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
              <div>

              <% else %>
                  <div class="nav-item">
                     <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
                  </div>
                  <div class="nav-item">
                     <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
                  </div>
              <% end %>
            </div>
        </div>
    </div>
</nav>

app/views/users/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a><%= link_to 'Enterprises', enterprises_path, class: "nav-link btn btn-primary ml-2" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a><%= link_to 'Dishes', dishes_path, class: "nav-link btn btn-primary ml-2" %></a>
      </li>  
      <li class="nav-item ">
        <a> <%= link_to 'Users', users_path, class: "nav-link btn btn-primary ml-2" %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a> <%= link_to 'Sign up', new_user_registration_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log in', new_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log out', destroy_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
  </form>
</div>
</nav>

<div class="row">
  <div class="col-md-12">
    <h1>Users <%= link_to 'New User', new_user_path, class: 'btn btn-success' %></h1>
  </div>
</div>

<hr>

<table class="table table-striped">
  <tr>
    <th>Image</th>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Address</th>
    <th>Actions</th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td>
          <% if user.picture.attached? %>
            <%= image_tag user.picture, size: 100 %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td>
          <%= link_to 'View', user_path(user) %>
          <%= link_to 'Edit', edit_user_path(user) %>
          <%= link_to 'Delete', user_path(user),
                      method: :delete,
                      data: {confirm: 'Do you want to remove this product?'} %>
        </td>
      </tr>
  <% end %>

</table>

app/views/users/show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Welcome</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a><%= link_to 'Enterprises', enterprises_path, class: "nav-link btn btn-primary ml-2" %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item ">
        <a><%= link_to 'Dishes', dishes_path, class: "nav-link btn btn-primary ml-2" %></a>
      </li>  
      <li class="nav-item ">
        <a> <%= link_to 'Users', users_path, class: "nav-link btn btn-primary ml-2" %> </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <a> <%= link_to 'Sign up', new_user_registration_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log in', new_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
      <a> <%= link_to 'Log out', destroy_user_session_path , class: 'nav-link btn btn-primary ml-2' %> </a>
  </form>
</div>
</nav>

<div>
  <div>
    <% if @user.picture.attached? %>
    <%= image_tag @user.picture, size: 100 %>
    <% end %>
  </div>
  <div>
  	<h1> <%= @user.name %> </h1>
    <p> <%= @user.email %> </p>
    <p> <%= @user.phone %> </p>
    <p> <%= @user.address %> </p>
  </div>
</div>